name: Telemetry System Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

jobs:
  test:
    name: Run Telemetry Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
        pip install -e .
    
    - name: Run tests with pytest and generate coverage report
      run: |
        pytest tests/ \
          --junitxml=test-results/junit.xml \
          --cov=telemetry_toolkit \
          --cov-report=xml \
          --cov-report=html
    
    - name: Generate test summary
      run: |
        python scripts/generate_test_report.py
      if: always()
    
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: |
          test-results/
          htmlcov/
          test_report.html
      if: always()
    
    - name: Post test summary comment
      uses: actions/github-script@v5
      if: github.event_name == 'pull_request'
      with:
        script: |
          const fs = require('fs');
          const summary = fs.readFileSync('test_report.html', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: summary
          });